spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: auth-service-route
          uri: http://localhost:8084
          predicates:
            - Path=/api/v1/auth/**

        - id: auth-api-docs
          uri: http://localhost:8084
          predicates:
            - Path=/auth/v3/api-docs/**
          filters:
            - StripPrefix=1

        - id: patient-service-route
          uri: http://localhost:8081
          predicates:
            - Path=/api/v1/patients/**
          filters:
            - JwtValidation

        - id: api-docs-patient-route
          uri: http://localhost:8081
          predicates:
            - Path=/patients/v3/api-docs/**
          filters:
            - StripPrefix=1
            - JwtValidation

authservice:
  url: http://localhost:8084

server:
  port: 8080

